# Generated by Django 5.0.6 on 2024-07-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrandmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
